#!/usr/bin/env bash

source "default.conf"
PASS_DIR=${pass_dir:-${PASSWORD_STORE_DIR:-${HOME}/.password-store}}

_rofi() {
    rofi -dmenu -p "Password"
}

list_passwords() {
    find -L "${PASS_DIR}" -name '*.gpg' | sed "s|$PASS_DIR/\(.*\).gpg|\1|"
}

copy_to_clipboard() {
    if [ -z "$1" ]; then
        exit
    fi
    pass show -c "$1" &> /dev/null

}

selected=$(list_passwords | _rofi)
copy_to_clipboard "$selected"
