#!/usr/bin/env sh

PASS_DIR=${PASSWORD_STORE_DIR:-${HOME}/.password-store}

list_passwords () {
    find -L "${PASS_DIR}" -name '*.gpg' | sed "s|$PASS_DIR/\(.*\).gpg|\1|"
}

list_passwords | rofi -dmenu

