#!/usr/bin/env bash

source "default.conf"
PASS_DIR=${pass_dir:-${PASSWORD_STORE_DIR:-${HOME}/.password-store}}

_rofi() {
    rofi -dmenu -p "Password"
}

list_passwords() {
    find -L "${PASS_DIR}" -name '*.gpg' | sed "s|$PASS_DIR/\(.*\).gpg|\1|"
}

list_passwords | _rofi

